// vue/src/components/detail.vue
<template>
  <div>
    <h1>Content details</h1>
    <h2>ID: {{ id }}</h2>
    <h2>Label: {{ label }}</h2>
    <h2>Content: {{ content }}</h2>
  </div>
</template>

<script setup>
// ====================
// Import
// ====================
import { ref, onMounted } from 'vue';
import { useRoute } from 'vue-router';


// ====================
// Const
// ====================
const route = useRoute();
const id = ref();
const label = ref();
const content = ref();

// ====================
// Functions
// ====================
async function getItemDetail(label, id) {
  const url = `http://localhost:3456/api/images/${label}/${id}`;

  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Response status: ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error(error.message);
  }
}


// ====================
// Life cycle
// ====================
onMounted( async () => {
  id.value = route.params.id;
  label.value = route.params.label;
  const item = await getItemDetail(label.value, id.value);
  content.value = item.content;
});

</script>

// react/src/components/Detail.jsx
import { useState, useEffect } from "react";
import { useParams } from "react-router-dom";

function Detail() {
  const { id, label } = useParams();
  const [content, setContent] = useState(null);

  useEffect(() => {
    async function fetchDetail() {
      const url = `http://localhost:3456/api/images/${label}/${id}`;

      try {
        const response = await fetch(url);

        if (!response.ok) {
          throw new Error(`Response status: ${response.status}`);
        }

        const item = await response.json();
        setContent(item.content);
      } catch (error) {
        console.error(error.message);
      }
    }

    if (id && label) {
      fetchDetail();
    }
  }, [id, label]);

  return (
    <div>
      <h1>Content details</h1>
      <h2>ID: {id}</h2>
      <h2>Label: {label}</h2>
      <h2>Content: {content}</h2>
    </div>
  );
}

export default Detail;
